/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Cities {
  city_name: Generated<string>;
  country_id: number;
  id: Generated<number>;
}

export interface Comments {
  comment: string;
  created_at: Generated<Timestamp>;
  gp_id: number | null;
  id: Generated<number>;
  reply_to_id: number | null;
  user_id: number;
}

export interface Countries {
  country_code: Generated<string>;
  country_name: Generated<string>;
  id: Generated<number>;
}

export interface Gps {
  city_id: number;
  finished: number | null;
  gp: number;
  id: Generated<number>;
  start_date: Timestamp | null;
  wild_card_id: number | null;
}

export interface Riders {
  country_id: number;
  id: Generated<number>;
  rider_name: Generated<string>;
  rider_number: number;
}

export interface RidersResults {
  gp_id: number;
  heats: Generated<number>;
  id: Generated<number>;
  podium: number | null;
  points: Generated<number>;
  rider_id: number;
}

export interface Users {
  auth0_id: Generated<string>;
  created_at: Generated<Timestamp>;
  email: Generated<string>;
  first_name: Generated<string>;
  id: Generated<number>;
  last_name: Generated<string>;
  reminder: Generated<number>;
}

export interface UsersPicksLog {
  created_at: Generated<Timestamp>;
  gp_id: number | null;
  id: Generated<number>;
  user_id: number | null;
}

export interface DB {
  cities: Cities;
  comments: Comments;
  countries: Countries;
  gps: Gps;
  riders: Riders;
  riders_results: RidersResults;
  users: Users;
  users_picks_log: UsersPicksLog;
}
